name: Commit Stamp
run-name: ${{ github.actor }} is testing automatic commit stamping
on: [push]
jobs: 
  Create-Commit-File:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: list-files
         run: ls ${{ github.workspace }}
